name: my python flask app
on: 
#  push: 
#    branches: 
#      - main
  workflow_dispatch:
env:
  docker_pass: ${{ secrets.DOCKER_PASS }}
  docker_user: ${{ secrets.DOCKER_USERNAME }}
  app_name: ${{ vars.IMAGE_NAME }}
jobs:
   avoid_redundancy:
     runs-on: "self-hosted" ##ubuntu-20.04
     steps:
       - name: Cancel Workflow Action
         uses: styfle/cancel-workflow-action@0.12.1
         with:
           access_token: ${{ github.token }}
   ruff_check:
     runs-on: "self-hosted"
     steps:
       - uses: actions/checkout@v4
       - name: ruff check
         uses: astral-sh/ruff-action@v1
   ruff_format:
     runs-on: "self-hosted"
     steps:
       - uses: actions/checkout@v4
       - name: ruff format
         uses: astral-sh/ruff-action@v1
         with:
           args: "format --check"
